root = "."
tmp_dir = "tmp"

[build]
  # Perintah build harus mengarah ke cmd/main.go
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  # Menjalankan binary hasil build dari folder tmp
  bin = "./tmp/main"
  # Pantau file dengan ekstensi ini
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  # Abaikan folder ini agar tidak looping build
  exclude_dir = ["assets", "tmp", "vendor", "frontend", "docker"]
  # Delay sebelum build ulang (ms)
  delay = 1000

[log]
  time = true