root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  include_dir = ["cmd", "internal", "pkg"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend", "docker"]
  delay = 1000

[log]
  time = true